build:
    environment:
        php:
            version: 7.1.1

    tests:
        override:
            -
                command: 'bin/phpspec run -c phpspec-ci.yml '
                coverage:
                    file: 'clover.xml'
                    format: 'clover'