build:
    environment:
        php:
            version: 7.1.3

    tests:
        override:
            -
                command: 'bin/phpspec run -c phpspec-ci.yml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
filter:
    paths: ["src/*"]
    excluded_paths:
        - "src/Dto/*"