language: php

branches:
  only:
    - master

php:
  - 7.0

before_install:
    - composer selfupdate

install:
    - composer update --no-scripts --no-interaction

script:
    - bin/phpspec run spec