#!/usr/bin/env php

<?php

// Autoload
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

// Setting up the Dependency Container
$container = new ContainerBuilder();
$container->setParameter('kernel.root_dir', __DIR__);
$loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/config/'));
$loader->load('parameters.yml');
$loader->load('services.yml');

// Fetching the application from the container
$application = $container->get('syncer.application');

// Run the application
$application->run();