Syncer\Dto\InvoiceNinja\Client:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            exlude: false
        name:
            type: string
            exclude: false
