Syncer\Dto\InvoiceNinja\Task:
    exclusion_policy: ALL
    properties:
        description:
            type: string
            exclude: false
        timeLog:
            type: string
            exclude: false
            serializedName: time_log
        clientId:
            type: integer
            exclude: false
            serializedName: client_id
