Syncer\Dto\InvoiceNinja\Project:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            exclude: false
        name:
            type: string
            exclude: false
        clientId:
            type: integer
            exclude: false
        isDeleted:
            type: boolean
            exclude: false
