Syncer\Dto\Toggl\TimeEntry:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            exclude: false
        pid:
            type: integer
            exclude: false
        tid:
            type: integer
            exclude: false
        uid:
            type: integer
            exclude: false
        description:
            type: string
            exclude: false
        start:
            type: DateTime
            exclude: false
        end:
            type: DateTime
            exclude: false
        updated:
            type: DateTime
            exclude: false
        duration:
            type: integer
            exclude: false
        user:
            type: string
            exclude: false
        useStop:
            type: boolean
            exclude: false
        client:
            type: string
            exclude: false
        project:
            type: string
            exclude: false
        projectColor:
            type: string
            exclude: false
        projectHexColor:
            type: string
            exclude: false
        task:
            type: string
            exclude: false
        billable:
            type: string
            exclude: false
        isBillable:
            type: boolean
            exclude: false
        cur:
            type: string
            exclude: false
        tags:
            type: array<string>
            exclude: false
