Syncer\Dto\Toggl\Workspace:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            exclude: false
        name:
            type: string
            exclude: false
