services:
    serializer_factory:
        class: Syncer\Factory\SerializerFactory
        arguments:
            - '%debug%'
            - '%serializer.config_dir%'
            - '%serializer.cache_dir%'

    serializer:
        class: JMS\Serializer\Serializer
        factory: 'serializer_factory:createSerializer'

    syncer.application:
        class: Symfony\Component\Console\Application
        calls:
            - [add, ['@syncer.command.sync_timings']]

    syncer.command.sync_timings:
        class: Syncer\Command\SyncTimings
        arguments:
            - '@toggl.client.toggl'
            - '@toggl.client.reports'
            - '@invoice_ninja.client'
            - '%clients%'
            - '%projects%'

    toggl.guzzle.toggl:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%toggl.toggl_base_uri%' , debug: '%debug%'}

    toggl.guzzl.reports:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%toggl.reports_base_uri%', debug: '%debug%' }

    toggl.client.toggl:
        class: Syncer\Toggl\TogglClient
        arguments:
            - '@toggl.guzzle.toggl'
            - '@serializer'
            - '%toggl.api_key%'

    toggl.client.reports:
        class: Syncer\Toggl\ReportsClient
        arguments:
            - '@toggl.guzzl.reports'
            - '@serializer'
            - '%toggl.api_key%'

    invoice_ninja.guzzle:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%invoice_ninja.base_uri%', debug: '%debug%'}

    invoice_ninja.client:
        class: Syncer\InvoiceNinja\InvoiceNinjaClient
        arguments:
            - '@invoice_ninja.guzzle'
            - '@serializer'
            - '%invoice_ninja.api_key%'
